### ISSUE TITLE
Can´t build

### ISSUE THREAD

**Issue by dvdrbls** [Sloth6/cymesh#1]
$ python3 setup.py build_ext --inplace
C:\Program Files\Python37\lib\site-packages\Cython\Compiler\Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\DELL\cymesh\cymesh\collisions\findCollisions.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
from __future__ import print_function
from libc.math cimport floor, fmin, fmax, fabs
from cymesh.mesh cimport Mesh
from cymesh.structures cimport Vert, Face, Edge
from cymesh.collisions.tri_intersection cimport tri_tri_intersection
from cymem.cymem cimport Pool
^
------------------------------------------------------------

cymesh\collisions\findCollisions.pyx:11:0: 'cymem\cymem.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from __future__ import print_function
from libc.math cimport floor, fmin, fmax, fabs
from cymesh.mesh cimport Mesh
from cymesh.structures cimport Vert, Face, Edge
from cymesh.collisions.tri_intersection cimport tri_tri_intersection
from cymem.cymem cimport Pool
^
------------------------------------------------------------

cymesh\collisions\findCollisions.pyx:11:0: 'cymem\cymem\Pool.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...

import numpy as np
cimport numpy as np

cpdef int[:] findCollisions(Mesh mesh) except *:
    cdef Pool mem = Pool()
        ^
------------------------------------------------------------

cymesh\collisions\findCollisions.pyx:17:9: 'Pool' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...

import numpy as np
cimport numpy as np

cpdef int[:] findCollisions(Mesh mesh) except *:
    cdef Pool mem = Pool()
                   ^
------------------------------------------------------------

cymesh\collisions\findCollisions.pyx:17:20: 'Pool' is not a constant, variable or function identifier

Error compiling Cython file:
------------------------------------------------------------
...
    nx = <int>((bbox[1] - bbox[0]) / maxd) + 1
    ny = <int>((bbox[3] - bbox[2]) / maxd) + 1
    nz = <int>((bbox[5] - bbox[4]) / maxd) + 1
    nynx = ny*nx

    cdef Node **grid = <Node **>mem.alloc((nx*ny*nz), sizeof(Node *))
                      ^
------------------------------------------------------------

cymesh\collisions\findCollisions.pyx:69:23: Casting temporary Python object to non-numeric non-Python type

Error compiling Cython file:
------------------------------------------------------------
...
    nx = <int>((bbox[1] - bbox[0]) / maxd) + 1
    ny = <int>((bbox[3] - bbox[2]) / maxd) + 1
    nz = <int>((bbox[5] - bbox[4]) / maxd) + 1
    nynx = ny*nx

    cdef Node **grid = <Node **>mem.alloc((nx*ny*nz), sizeof(Node *))
                      ^
------------------------------------------------------------

cymesh\collisions\findCollisions.pyx:69:23: Python objects cannot be cast to pointers of primitive types

Error compiling Cython file:
------------------------------------------------------------
...
    nx = <int>((bbox[1] - bbox[0]) / maxd) + 1
    ny = <int>((bbox[3] - bbox[2]) / maxd) + 1
    nz = <int>((bbox[5] - bbox[4]) / maxd) + 1
    nynx = ny*nx

    cdef Node **grid = <Node **>mem.alloc((nx*ny*nz), sizeof(Node *))
        ^
------------------------------------------------------------

cymesh\collisions\findCollisions.pyx:69:9: Storing unsafe C derivative of temporary Python reference

Error compiling Cython file:
------------------------------------------------------------
...
            print(list(v1.p))
            print(list(v2.p))
            print(list(v3.p))
            assert False

        node_a = <Node *>mem.alloc(1, sizeof(Node))
                ^
------------------------------------------------------------

cymesh\collisions\findCollisions.pyx:115:17: Casting temporary Python object to non-numeric non-Python type

Error compiling Cython file:
------------------------------------------------------------
...
            print(list(v1.p))
            print(list(v2.p))
            print(list(v3.p))
            assert False

        node_a = <Node *>mem.alloc(1, sizeof(Node))
                ^
------------------------------------------------------------

cymesh\collisions\findCollisions.pyx:115:17: Storing unsafe C derivative of temporary Python reference
['cymesh', 'test', 'cymesh.collisions', 'cymesh.operators', 'cymesh.subdivision']
Compiling .\cymesh\mesh.pyx because it changed.
Compiling .\cymesh\shape_features.pyx because it changed.
Compiling .\cymesh\structures.pyx because it changed.
Compiling .\cymesh\collisions\findCollisions.pyx because it changed.
Compiling .\cymesh\collisions\tri_intersection.pyx because it changed.
Compiling .\cymesh\operators\relax.pyx because it changed.
Compiling .\cymesh\subdivision\sqrt3.pyx because it changed.
[1/7] Cythonizing .\cymesh\collisions\findCollisions.pyx
Traceback (most recent call last):
  File "setup.py", line 29, in <module>
    include_path = [numpy.get_include()],
  File "C:\Program Files\Python37\lib\site-packages\Cython\Build\Dependencies.py", line 1097, in cythonize
    cythonize_one(*args)
  File "C:\Program Files\Python37\lib\site-packages\Cython\Build\Dependencies.py", line 1220, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: .\cymesh\collisions\findCollisions.pyx

What can I do?
Thanks

**Comment by joel-simon** [comment]
Hi, seems like you need to install https://github.com/explosion/cymem

I should have that in the requirements file. This is very experimental code btw and not fully tested.

Best,
joel
