### ISSUE TITLE
There is a bug in face area calculation.

### ISSUE THREAD

**Issue by tak0kada** [Sloth6/cymesh#2]
Currently, the area of a face is calculated by `std::sqrt(d) / 16`, although we find in the [reference](http://www.iquilezles.org/blog/?p=1579), A² = (2ab + 2bc + 2ca – a² – b² – c²)/16. It should correctly be `std::sqrt(d / 16)`.

**Comment by tak0kada** [comment]
I created a [pull request](https://github.com/joel-simon/cymesh/pull/3). Sorry if there is some mistake in the GitHub usage.

**Comment by joel-simon** [comment]
Good catch! Thank you for submitting a PR :) I hope the library is useful for you.
